### ISSUE TITLE
Design MVP developer profile page

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/pot-websites#107]
Design Developer profile page which is used in developer portal. Accessible from developers.oftrust.net/profile (suggest better)

In the opening view: 

* Developer can list API Tokens (issued date, valid until date)
* Add first name, last name
* Add link to Github profile
* Add link to wanted website

* List Applications created / can manage (name, created date, possibly description, logo, App ID)
* List Created data products (name, created date, possibly description, logo, product ID)

## Acceptance criteria

- [x] Wireframe design screenshot attached to this issue
- [x] PO and UX lead approves design (reviews from them)

**Comment by Nazarah** [comment]
@kyyberi  I have a clarification to make. Is this profile going to be only developers' portal specific? Because, if at somepoint, PoT users can access all three services (e.g. MyWorld, Developers' Portal and MarketPlace) using single sign-in, shouldn't each user have a single profile rather than platform specific ones?

**Comment by kyyberi** [comment]
This is Developer Portal specific

**Comment by Nazarah** [comment]
### Mobile 1st version

1. App View

1st view of API Profile would be the list of Apps the Developer owns or Manages. Apps appear as cards with name, id and created  date

![AppView](https://user-images.githubusercontent.com/17976243/58945251-4e07d300-87a5-11e9-9c91-c71adb9e3de6.png)

**Comment by Nazarah** [comment]
**3. App Access Token**

In This view, developer can modify App Access Tokens for the Apps he owns or manages

![App Access Token](https://user-images.githubusercontent.com/17976243/58945570-ea31da00-87a5-11e9-9aeb-4497b6c6bac1.png)

![App Access Token Edit](https://user-images.githubusercontent.com/17976243/58945588-f158e800-87a5-11e9-90be-5fe50dbab5d5.png)

**Comment by Nazarah** [comment]
**4. API Tokens**

In this view, users can list API tokens that s/he might use later.
Tokens appear with  creation and valid until dates
API tokens can be copied and deleted when they are expiration.

![API Access Token](https://user-images.githubusercontent.com/17976243/58945705-31b86600-87a6-11e9-9e02-0843d98d3bb9.png)

**Comment by Nazarah** [comment]
**5. Account Settings**

RIght now, user can change his password settings from this place.
In future, other profile related settings can be added here.

![Account Settings](https://user-images.githubusercontent.com/17976243/58945794-58769c80-87a6-11e9-9ddb-772ee97701ef.png)

**Comment by Nazarah** [comment]
**6. Edit Profile information**

Basic information about a user appears on top part of the profile.
By clicking Edit Profile, User can modify everything  except username and email (the one s/he signed  up with to PoT)

![EditView](https://user-images.githubusercontent.com/17976243/58945980-b99e7000-87a6-11e9-8d35-cc42472728b5.png)

**Comment by Nazarah** [comment]
### Desktop View

A user can edit his profile bio (except email and username) from Desktop View
Views consisting Apps and Data Products has search functionality, which can be filtered according to Sandbox and Production

**App View**
![DT App View](https://user-images.githubusercontent.com/17976243/59253778-c3195380-8c50-11e9-8d45-515c44d3e676.png)

**Data Product View**
![DT Data product View](https://user-images.githubusercontent.com/17976243/59253819-d5938d00-8c50-11e9-9d7d-ddbeea2e6692.png)

**App Access Token View**
![DT App Access Token View](https://user-images.githubusercontent.com/17976243/59253842-e2b07c00-8c50-11e9-8384-30e57778ce0c.png)

**Account Settings View**
![DT Account Settings](https://user-images.githubusercontent.com/17976243/59253871-f2c85b80-8c50-11e9-82dd-71a889c9e7e5.png)

**Comment by hsuomi** [comment]
Conclusions from today's developer portal MVP meeting (present Nazia, Henna & Kari). From the very first version, we should leave out the the links to market place, MyWorld, let's just have the first developer views for the developers to register themselves and their organization to the platform and to create apps and data products, change their password if needed. 
- Desktop version is great (we don't need the mobile yet)
- From the first version, let's leave out all the social media links, titles etc as they are not needed by the first developers yet

I'll specifiy the envisioned user flow in confluence

**Comment by kyyberi** [comment]
I agree with the above as long as the implementation takes mobile view into account even though first view is desktop. Converting complex desktop UI/UX to something that works in mobile is a pain in the ass if not impossible sometimes. Mobile view should not be looked down; architects and developers take a look at the platform from mobile in meetings and conferences.

**Comment by soderluk** [comment]
Regarding the labels of sandbox and production for apps and data products. You need to be signed in to either environment to be able to list things, either sandbox or production. I don't think that it's possible to list things that are in different environments in one app. @kyyberi

**Comment by kyyberi** [comment]
Hmmm... that is right @soderluk. Although if the apps and products in sandbox and in production are set visible/ public to all, then it should be public. With API I can list all products (currently) in sandbox via Product API. That is not the case for all though. And that probably will not be the case in the future either. 

We should nevertheless find as way to list both sandbox and production env apps and data products managed / owned by the user since otherwise the listing does not make sense.

**Comment by soderluk** [comment]
@kyyberi: I'm not entirely sure that it will be possible even by the backend. As I mentioned, sandbox and production are two separate environments, with separate identities and apps and data products etc.
When you log in, you log in to the respective environment. The GET endpoints are public, so in that way, yes, you can query all data products from the different environments, but you cannot edit a production data product if you're logged in to the sandbox environment. Also, there's the issue about listing only YOUR data products, since it requires the bearer token to match the environment.

**Comment by kyyberi** [comment]
I see. Hmm....product API GET does not require tokens (https://docs.oftrust.net/#products-v1). But yes, editing any object is a different thing. It becomes rather complex for the developer to switch from env to another while working. REady to accept that for now, but for sure we should aim to find a more developer (consumer) friendly manner than log out - log in constantly to fiddle with products.
