### ISSUE TITLE
Design MVP version of frontpage API testing block

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/pot-websites#108]
**Update:** Let's start with the 1st version of the design. 

Design Developer Portal frontpage block which offers instant testing of our CORS enabled APIs. In the future we'll probably have a way to add non-CORS APIs there as well. Current list of CORS enabled API endpoints are: 

* GET /products/v1/
* GET /products/v1/{product_code}

Follow the example of stripe.com, but don't just blindly copy it. 

<img width="1016" alt="Näyttökuva 2019-5-14 kello 10 44 50" src="https://user-images.githubusercontent.com/1927158/57680015-53a24b00-7635-11e9-9e81-0ce80d2b811a.png">

Keep in mind that we'll find a way to add more API endpoints to be used. 

Implementation of the design will take place in Sprint 25 (6.6.-19.6.)

## Acceptance criteria

- [x] Wireframe design screenshot attached to this issue
- [ ] PO and UX lead approves design (reviews from them)

**Comment by kyyberi** [comment]
Runkit codes done in #92

**Comment by Nazarah** [comment]
### Mobile Version

The **Runkit Module** appears right after **What You Want to do Next** section in Developers' Portal homepage.
Section Name: Try Our APIs
Section Text:
>Make instant test calls to our Product API to list all available Data Products and
see the Details of one Data Product. Capabilities of testing other APIs will be
expanded soon. 
For **Product API**, **2 options** are available: **List All Products** and **Get A Data Product**.
On selecting one option, corresponding code snippet appears on the Runkit UI.

![ListDataProductsMobileV1](https://user-images.githubusercontent.com/17976243/58765553-f1829900-8595-11e9-8f79-949ae61d102f.png)


![GetOneDataProductV1Mob](https://user-images.githubusercontent.com/17976243/58765557-fe06f180-8595-11e9-829c-b2c6eb8ccef2.png)

Link redirecting to API Documentation site appears after the module.

**Comment by Nazarah** [comment]
### Desktop Version

![ListDataProductsV1](https://user-images.githubusercontent.com/17976243/58765598-72da2b80-8596-11e9-9445-2208d8b0f058.png)


![GetOneDataProductV1](https://user-images.githubusercontent.com/17976243/58765605-7d94c080-8596-11e9-9636-dc7c50a7e30a.png)

**Comment by Nazarah** [comment]
### Alternate Design

**1. Mobile version**

For **Product API**, **2 options** are available: **List All Products** and **Get A Data Product**.
On selecting one option, corresponding code snippet appears on the Runkit UI.

![ListDataProductsMobileV1](https://user-images.githubusercontent.com/17976243/58777848-0d1b8d00-85f2-11e9-8bc3-5d73a411b885.png)

![GetOneDataProductV1Mob](https://user-images.githubusercontent.com/17976243/58777858-1a387c00-85f2-11e9-8b3a-d953c82aa0c4.png)

**2. Desktop version**

![ListDataProductsV1](https://user-images.githubusercontent.com/17976243/58777881-3a683b00-85f2-11e9-8cf7-8fb59db6802f.png)


![GetOneDataProductV1](https://user-images.githubusercontent.com/17976243/58777894-43590c80-85f2-11e9-8f44-54c62e5864e1.png)

**Comment by kyyberi** [comment]
At this point I would go with the option where the 2 runkits are one after another. After we get more APIs (endpoints) in the block, we'll transfer (most likely) to the design in which runkits are in one block and content changes when selecting the API to try.

**Comment by kyyberi** [comment]
@MikaHamalainen review still needed

**Comment by MikaHamalainen** [comment]
I really don't know what you are doing here? Trying to redesign RunKit? Good luck with that...

Otherwise, I don't have anything to complain :-)

**Comment by MikaHamalainen** [comment]
Might be more relevant when we get RunKit embedded.

**Comment by kyyberi** [comment]
What is stopping us to do this? :) Embedding runkit is adding JS to the site. Needed runkit examples (content) is already done:
* https://runkit.com/kyyberi/product-api-v1--get-one-dataproduct 
* https://runkit.com/kyyberi/product-api-get-products

Runkit does not provide off the shelve solution to embed multiple runkits in one block (afaik). Correct me if you have different information.  

The question design-wise was only what makes sense now: 
1) Put those as separate runkits in the frontpage or
2) Do some div magic and swap runkit to show based on which of the examples user wants to test.

**Comment by kyyberi** [comment]
I would say that we are ready to implement this anytime (next or following sprint)

**Comment by MikaHamalainen** [comment]
gatsby-remark-embed-runkit doesn't seem to work.

**Comment by Nazarah** [comment]
Reply to [comment](https://github.com/PlatformOfTrust/pot-websites/issues/108#issuecomment-498738840) 

No, any fantasy design or reinvention of runkit UI is being done here. :)
If you go to [stripe](https://stripe.com/en-fi), you would see a runkit UI and I simply used its reference in the wireframes. 
Same UI references were used in API profile page wireframe.
Runkit  examples of the product API GET http requests are  [here ](https://runkit.com/kyyberi/product-api-get-products)and [here](https://runkit.com/kyyberi/product-api-v1--get-one-dataproduct).
Whatever version of Runkit UI you feel fit to be embedded in Developer Portal, proceed with that.
