### ISSUE TITLE
Possible travis build failure due to missing font awesome pro configuration

### ISSUE THREAD

**Issue by Nazarah** [PlatformOfTrust/pot-websites#116]
**Describe the bug**
build fails due to absence of token for font awesome pro version 

**Solution**
travis build configuration needs to be modified to include the fontawesome pro version.
Details are given in the [documentation](https://github.com/PlatformOfTrust/pot-websites/tree/rel2) of rel2 branch for marketing-site.

**Comment by kyyberi** [comment]
npmrc and TOKEN required was added and Travis configured to know the required TOKEN done. Build still fails.

**Comment by kyyberi** [comment]
Fixed
