### ISSUE TITLE
Create UX / Usability Report Template

### ISSUE THREAD

**Issue by Nazarah** [PlatformOfTrust/pot-websites#117]
Create a template that can be used to report UX or Usability Evaluation of Different PoT Services. The template should increase readability and make it possible to present in in meetings.

***Must Have***
- [ ] a general template (with instructions) that can be used in future
- [x] one previous report (text-based) converted into the template format
- [ ] placeholder for texts, links, pictures, diagrams, etc.
- [x] consistent with PoT Guidelines

***Should be***
- [ ] reviewed and accepted by Developer Program Lead

**Comment by kyyberi** [comment]
Implement in typeform

**Comment by Nazarah** [comment]
@kyyberi 
replying to [comment](https://github.com/PlatformOfTrust/pot-websites/issues/117#issuecomment-494706789)

I checked out a demo of typeform. What I understood it that I can create survey questionnaire and send it to the reviewers, so that they can write down their findings and feedback. However, to make the reports concise and to make sure people actually read them, we need to fine tune them ourselves. 
I am taking reference from [this article](https://uxdesign.cc/how-to-write-a-user-testing-report-that-people-will-actually-read-652d15d2f92e) to build the 1st version with PPT.
I will provide both PDF and ppt slideshow for the first version.

**Comment by Nazarah** [comment]
[Developer Portal Review Report.pdf](https://github.com/PlatformOfTrust/pot-websites/files/3226378/Developer.Portal.Review.Report.pdf)
[Developer Portal Review Report.pptx](https://github.com/PlatformOfTrust/pot-websites/files/3226392/Developer.Portal.Review.Report.pptx)
@kyyberi 1st version of review report both in PDF and ppts slide show

**Comment by Nazarah** [comment]
Will transfer contents to PoT Specific PPT and upload it in specific location. Reviewed done.
