### ISSUE TITLE
Script to launch commercial site on local machine

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/pot-websites#120]
**Is your feature request related to a problem? Please describe.**
Commercial site PO is mostly marketing oriented person and needs easy access to see what is the status of site development. Until we have staging version for that, we need to have a workaround. 

**Describe the solution you'd like**
Simple shell script which: 
* Pulls the source code from github (branch name given as input)
* Do the build (see commands from README)
* Launch browser and show result locally. 

It is assumed that for example git client (cli) is installed on the users machine. Also, the usage environment is primarily macbook pro Mojave (10.14.5). 

Push the script to pot-websites repository as `launch-commercial-site.sh`.

**Comment by Nazarah** [comment]
@kyyberi  
1. Open a terminal, open a file named launch-commercial-site.sh using nano and copy-paste the following below.

```
#script pulls the latest change from pot-website and runs the site in localhost
#It is assumed that for example git client (cli) is installed on the users mach$
#Also, the usage environment is primarily macbook pro Mojave (10.14.5).

#Go to the specific GitHub Repository, check status, make a pull

cd
cd Documents/GitHub/pot-websites
echo -n "Enter the full branch name (e.g.master or feature/branch-name): "
read name
git checkout $name
git status
git pull

#Navigate to commercial site and launch it

cd marketing-site
npm install
gatsby develop -o -p 8000
```
2. Exit to terminal and type the following two commands.
`chmod launch-commercial-site.sh`
`chmod 777 launch-commercial-site.sh`

3. launch the script with the command:  `./launch-commercial-site.sh`
