### ISSUE TITLE
Fix README repo cloning command

### ISSUE THREAD

**Issue by karihovi** [PlatformOfTrust/pot-websites#124]
Fix cloning command in README instructions to:

`git clone https://github.com/PlatformOfTrust/pot-websites.git`

This is the same link you get from the clone button.

**Comment by kyyberi** [comment]
It depends which do you prefer to use: https (https://github.com/PlatformOfTrust/pot-websites.git), or SSH based (git@github.com:PlatformOfTrust/pot-websites.git). Both work.
