### ISSUE TITLE
Register as user / login

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/pot-websites#6]
As API Consumer I want instantly register with existing github account  as new user to maintain own profile in portal.

**Comment by lietu** [comment]
We probably don't have time to implement GitHub login in the near future. And the `login` component handles user sign up and login. It's only now being built.

**Comment by kyyberi** [comment]
So we could build the front-end now and connect to backend as soon as possible? 
This is related to #18 as well since the developer profile has to be shown somehow.

**Comment by kyyberi** [comment]
Sign up can start from 3 places: 
1. menu item with "sign up"
2. For Developers section top part by giving email address in the field provided and hitting"signup".  
3. Bottom of the For Developers section by giving email address in the field provided and hitting"signup". 

In the options 1 and 2. given email is forwarded to signup form and user provides other information required in that view.

**Comment by kyyberi** [comment]
Does the login component enable calling it with params such as email described above? @lietu probably knows this best.

**Comment by lietu** [comment]
The login system has been implemented similar to `Login with Facebook` -buttons everywhere. A user of the login component cannot direct it to target log in or sign up form, nor give it any initial data.

**Comment by kyyberi** [comment]
Ok, we'll just put a buttons Register and Login

**Comment by kyyberi** [comment]
the login is an OAuth 2.0 authorization grant -flow, it needs a backend, that the website doesn't have.

**Comment by kyyberi** [comment]
Moved to Q3
