### ISSUE TITLE
Create new data product UI sketch

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/pot-websites#60]
**As a:** developer 
**I want to:** create new data product to market place
**so that:** other developers can build new apps on top of our data

**Comment by kyyberi** [comment]
![data-product-1](https://user-images.githubusercontent.com/1927158/52117285-05d07c80-261c-11e9-9b27-fc6c7c59bab0.jpg)

## 1. Read Getting started with data product
User goes to For developers section and clicks "HOW TO CREATE DATA PRODUCTS" and is taken to page which describes the process what has to be done to create new data product. 

This page is created in task # TBD

## 2. Setup translator
In practise developer builds an API which translates source data format to PoT compatible data models using given ontologies. 

Developer is instructed to download or clone Translator python skeleton from Github https://github.com/PlatformOfTrust/translator-skeleton-python and read readme.md which includes needed information to understand what it is and how to set it up. 

Developer needs also information package of ontologies used in PoT. Should be linked to "Getting started package". This page is created in task: # TBD

Developer implements the data transformation rules in translator. 

Developer deploys the translator to wanted service or platform for example AWS or Heroku. 

## 3. Register Translator

Developer opens "Translators" view in portal (needs to be logged in). The view lists all translators this given developer has created and/or can manage. 

Developer clicks "Add translator" button

Developer is shown a form which contains following data fields: 
- Translator Name
- Short desc
- Status: development, testing, production
- Visibility: private, organisation, public(?)
- Translator access point URL:

**Comment by kyyberi** [comment]
I will create first sketches today (wedn).

**Comment by Nazarah** [comment]
I have made primary sketches of the Add Data Product process based on the documentation in Pot-Website Developers' Portal and some of my own assumption. I am adding sketches of every step in this userflow in separate comments for the ease of readability and understanding. The sketches are in mobile 1st approach:

### Login / SignUp to start Adding Data Product

A User can access the action from
1. **hamburger menu** in PoT Developers' Portal
2. **Add Data Product card** under "What do you want to do next?"  section or
3. Bottom of Data Product 101 page in Developers' Portal

![Screen Shot 2019-04-23 at 11 31 29](https://user-images.githubusercontent.com/17976243/56566455-5de3a300-65bb-11e9-9733-159843a9517b.png)

In any case, the user needs to have an account at PoT (developer's portal / MyWorld / Market Place) and needs to be logged in

**Comment by Nazarah** [comment]
### 1 Basic Information

In the **1st** of the 6-step process, a user needs to provide some basic information (as mandatory fields) about the data product: 
**Name**
**Description**
**Consumers:** added as labels when typed and entered in the field. Also removable.
**Usecases**: added as json/yaml extensions (anything else?); multiple files can be added; files can also be removed.
**URL of Beta API**: API for authorization purpose.

![Screen Shot 2019-04-23 at 11 35 37](https://user-images.githubusercontent.com/17976243/56567277-38f02f80-65bd-11e9-8551-9c085cba1890.png)

fields are self-explanatory.
URL syntax checking is needed to Beta API
[What is Data Product?](https://developer.oftrust.net/guides/data-products) link redirects user to the Data Product 101 page in Developers' Portal.
**Next** button is activated only when all mandatory fields are filled.

**Comment by Nazarah** [comment]
### 2 Data Access Authorization

User needs to select some authorization scheme for consumers to access the data. 
This can be done by either 
1. an **authentication protocol** or 
2. an **authorization API** (provided as URL or API Documentation)

![Screen Shot 2019-04-23 at 11 52 28](https://user-images.githubusercontent.com/17976243/56567751-3fcb7200-65be-11e9-8a9d-76534d1d6717.png)

**N.B.** Needs clarification from @kyyberi  to confirm whether this step is right? Or this can also be implemented in the 1st step. Made on assumptions.

**Comment by Nazarah** [comment]
### 3 Select Translator

A user can select a translator via
1. Tunninen Oy ( I am not sure how the trial / payment is going to work here. Need more input on this) 
Or,
2. One provided from Platform Of Trust ( here, I am assuming user maps the local data attributes with PoT Onthologies in the downloaded python file)
![Screen Shot 2019-04-23 at 12 43 01](https://user-images.githubusercontent.com/17976243/56571312-532e0b80-65c5-11e9-9cc7-33f88269f5d5.png)

For selecting 2nd options, users are provided with download link ([here](https://github.com/PlatformOfTrust/translator-skeleton-python)) and additional information to use the demo python skeleton

Users are also provided with additional links to [Set Up a Translator](https://developer.oftrust.net/guides/translator), [Using Standard Data Models](https://developer.oftrust.net/guides/data-models) and [Platform of Trust Onthologies](https://standards.oftrust.net/).

**N.B.** (I have questions regarding to mapping local data attributes to PoT Standards. 
Should this be done in the skeleton file? 
Or there should be another step after adding a translator, where the GUI would populate User's Local Data Attribute, PoT Standards and some pairing mechanism to map local attributes to standards? How user would select an optimal PoT data standard that is closest to that of his local data attribute?)
Or would there be any 3rd party app to perform this mapping?)

**Comment by Nazarah** [comment]
### 4 Sandbox Registration

The User needs to generate a **CURL** request to register the data product to the PoT Sandbox.
Fields are used to generate different part of the Authorization header.
User can check as **authorization CURL request example** by clicking the link [Sample API Call for Registration](https://developer.oftrust.net/guides/data-products) (navigated to the specific section)
**Generate Curl** button is active when all mandatory fields are fulfilled.
![Screen Shot 2019-04-23 at 13 05 51](https://user-images.githubusercontent.com/17976243/56572825-7e662a00-65c8-11e9-818b-95defad9e6af.png)


After generating the curl request, a user can authorize the data product by clicking **Authorize** button (alternatively copying the curl request and using terminal/postman/insomnia to do the above). On success, the user can see the related status code and response header. 

A sample API call request is given for to the user afterward to test the data in the sandbox environment. User can also access [Data Broker API Documentation](https://docs.oftrust.net/#broker-api) from the given link

**Need Clarification:** 
1. Should this step be done using **Postman/Insomnia** app? Or
2. there should be a **console in the UI** where the user needs to compose the curl example him/herself?

**Comment by Nazarah** [comment]
### 5. Production Registration

Similar UI as that of the previous step.
User simply needs to provide production data URL instead of Translator URL and make the CURL call the PoT Product API (for convenience, this field value is hardcoded)
![Screen Shot 2019-04-23 at 13 34 44](https://user-images.githubusercontent.com/17976243/56574727-a061ab80-65cc-11e9-9cca-14180a1e9d80.png)

User can also check [Product API Documentation](https://docs.oftrust.net/#product-api) for more help.

**Comment by Nazarah** [comment]
### 6. Preview and Finalization

In this UI, a user gets to see a **preview** of field values and tests made in the previous steps before s/he can finalize adding the data product.

![Screen Shot 2019-04-23 at 13 39 24](https://user-images.githubusercontent.com/17976243/56574949-30075a00-65cd-11e9-9448-b006cd17b291.png)

A User can go back to previous steps by clicking **Previous** buttons. User can also cancel the entire process by clicking **Cancel**.

**Comment by soderluk** [comment]
Regarding: https://github.com/PlatformOfTrust/pot-websites/issues/60#issuecomment-459678958
The steps 3-5 are actually the same thing, you create a data product, and that's enough. The data product contains all information needed about the translator and the data to be passed to it, as well as the data to be returned to the requester.

**Comment by soderluk** [comment]
Regarding: https://github.com/PlatformOfTrust/pot-websites/issues/60#issuecomment-485709957
What is needed (* are mandatory):
- product code *
- name *
- description *
- translator URL *
- organization public keys * (URL and type)
- data context * (describes the data that the translator returns)
- parameter context * (describes the parameters that are sent to the translator)
- image URL (a URL to a product image)

Everything else in the UI is redundant, and not used. E.g. consumers, use cases, access via protocol/access via api.

**Comment by soderluk** [comment]
Regarding: https://github.com/PlatformOfTrust/pot-websites/issues/60#issuecomment-485731060
and https://github.com/PlatformOfTrust/pot-websites/issues/60#issuecomment-485740861
They are both redundant. The whole "create data product" is created by using the information in my previous comment.
The data products should always be registered first to the sandbox, tested and edited there, and only when the sandbox is working, should the data product be created in production.
The process is exactly the same, except the URL is pointed to the production URL instead.

**Comment by soderluk** [comment]
Regarding: https://github.com/PlatformOfTrust/pot-websites/issues/60#issuecomment-485750716

Once we have the backend for the developer portal, we should be able to test out the actual created data product. This should be a separate endpoint in the developer portal backend, and should be planned into sprints.

**Comment by Nazarah** [comment]
Thanks @soderluk for the feedback.
Based on your [feedback](https://github.com/PlatformOfTrust/pot-websites/issues/60#issuecomment-487540944) I redesigned the UI wireframes and now it's a two step process.

1. 1st step prompts user to **fill up** mandatory fields, **Register** the Data in `Sandbox` and **Test** the data (according to this [feedback](https://github.com/PlatformOfTrust/pot-websites/issues/60#issuecomment-487541748)).
User can only move forward when the above works are completed successfully.

![Screen Shot 2019-04-30 at 12 54 38](https://user-images.githubusercontent.com/17976243/56954884-a1ed1f80-6b48-11e9-826e-3eea2a93453d.png)

In case of an error with Sandbox registration or Data testing, user won't be able to move to the 2nd step.
![Screen Shot 2019-04-30 at 12 55 02](https://user-images.githubusercontent.com/17976243/56954940-c0ebb180-6b48-11e9-88af-f6aae6635c17.png)


2. The 2nd step is finalizing the Create Data Product workflow by **registering** the data product in the **Production environment**. 
Registering the production can be done only when Sandbox Data is registered and tested before.
![Screen Shot 2019-04-30 at 12 55 08](https://user-images.githubusercontent.com/17976243/56955033-fbede500-6b48-11e9-8db5-141206aaff80.png)

On successful registration to the production environment, the user can finish creating the data product.
In any error case, the user is advised to contact the system administrator.

![Screen Shot 2019-04-30 at 12 55 15](https://user-images.githubusercontent.com/17976243/56955155-42434400-6b49-11e9-9346-480127ab7d27.png)


**N.B.** error codes returned by related API depends on the nature of error occured.

**Comment by MikaHamalainen** [comment]
Nice work. I would move "What is DataProduct" - link from bottom to start.
