### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Nazarah** [PlatformOfTrust/pot-websites#75]
Current README is obsolete. Developers' Portal Repo can't be set up and run in localhost following the instructions there. No Gatsby folder can be found

**To Reproduce**
1. Clone the repo in your local machine.
2. Open terminal, go to the folder of the repo in your machine and type `ls -s`

**Expected behavior**
Should show a folder named gatsby for the user to navigate and execute other commands needed.

**Actual Result**
No Gatsby folder is found

**Screenshots**
<img width="834" alt="Screen Shot 2019-03-28 at 11 08 35" src="https://user-images.githubusercontent.com/17976243/55144438-85288b00-5149-11e9-8ee1-04ae766fc0a1.png">

**Desktop (please complete the following information):**
 - OS: MAC
 - BrowserChrome

**Additional context**
tried to delete the repo in the local machine because it was having problems to start and run.
Decided to clone the repo from GitHub.

**Comment by MikaHamalainen** [comment]
Readme updated
