### ISSUE TITLE
Content disappears on return with browser back button

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/pot-websites#81]
**Describe the bug**
Content of the website just vanishes on return from other website. 

**To Reproduce**
1. Go to https://developers.oftrust.net/apis
2. Click on link https://docs.oftrust.net/#authentication from first box labelled "Authentication"
3. Click back button from browser

**Expected behavior**
Show the content as it was before visiting elsewhere

**Screenshots**
https://www.youtube.com/watch?v=ryHHM6HB5EE&feature=youtu.be

**Desktop (please complete the following information):**
 - OS: iOS mojave 10.14.3 (18D109)
 - Browser Firefox
 - Version 66.0.2 (64-bit)

**Comment by MikaHamalainen** [comment]
I'll research.
Related: https://github.com/gatsbyjs/gatsby/issues/2750

**Comment by MikaHamalainen** [comment]
Solved: Always inject MarkDown fragment inside container element as <div> - not inside something as <p> :-) 
<div className="content-fragment" dangerouslySetInnerHTML={{ __html: node.html }} />
