### ISSUE TITLE
Items should be in two columns

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/pot-websites#82]
**Describe the bug**
The items listed in the page as boxes are now on top of each other and thus a lot of empty space is left on the right side. That looks ugly and impractical. 

**To Reproduce**
1. Go to https://developers.oftrust.net/apis
2. See error

**Expected behavior**
The boxes should be listed in 2 columns in full-page view, mobile view is a different thing. 

**Screenshots**

<img width="900" alt="Näyttökuva 2019-4-7 kello 15 43 45" src="https://user-images.githubusercontent.com/1927158/55683794-62b61f00-594c-11e9-92d0-21747eff6bfe.png">

**Desktop (please complete the following information):**
 - OS: iOS Mojave 10.14.3 (18D109)
 - Browser: Firefox 66.0.2 (64-bits)

**Comment by MikaHamalainen** [comment]
Current breakpoint for them is 767px, so iPad would still be 2-col, anything smaller 1-col. 
No bug, readability decision.

Check your browser width and zoom level.

**Comment by MikaHamalainen** [comment]
There seems to be issue in Firefox and Bootstrap. Reopening issue.

**Comment by MikaHamalainen** [comment]
Some versions of firefox intepreded bootstrap card-columns default value column-count value differently. Solved by skipping card-columns class altogether.

Still need testing.
