### ISSUE TITLE
Design API Profile page

### ISSUE THREAD

**Issue by kyyberi** [PlatformOfTrust/pot-websites#96]
Design single API profile page which is used in developer portal. All the APIs are listed under /apis and from there will be link to API profile page which provides detailed view / introduction to the API at hand

See for example from #91 and #95 what is expected to be in content. 

In Design create a full page with all the information (must / would like to have. Design to be done so that we can first implement `must have` elements and add with minimum friction the `would like to have` content.

Implementation of the design will take place in Sprint 24 (23.5.-5.6.)

## Acceptance criteria

- [x] Wireframe design screenshot attached to this issue
- [ ] PO and UX lead approves design (reviews from them)

**Comment by Nazarah** [comment]
###  Mobile 1st Designs

API profile is divided into 6 sections: General, Documentation, Sandbox, Resources, Production Analytics and Feedback. Each section can be reached quickly from secondary menu (green hex button). Profile is scrollable and hex indicators (on right side) shows on which section the user is currently in.

1. General

Contains information: **Add Date**, **Version**, **Availability(uptime) statistics**, **Brief Description**, **Capabilities and Limitations**.
CTAs: **Try out with Runkit** (onClick --> Takes user to erlated Sandbox section; [Link to API documentation](https://docs.oftrust.net/?shell#broker-api)


<img width="789" alt="Screen Shot 2019-05-08 at 11 48 07" src="https://user-images.githubusercontent.com/17976243/57362247-0fbbcb80-7187-11e9-9e9f-beffd9814956.png">

<img width="370" alt="Screen Shot 2019-05-08 at 11 41 14" src="https://user-images.githubusercontent.com/17976243/57362265-19453380-7187-11e9-83bc-8a1431411f37.png">

**Comment by Nazarah** [comment]
**2. Documentation**

This section shows a [link](https://docs.oftrust.net/?shell#broker-api) to view the API documentation in doc.oftrust.net

<img width="365" alt="Screen Shot 2019-05-08 at 12 15 25" src="https://user-images.githubusercontent.com/17976243/57364028-f9b00a00-718a-11e9-8223-b35ad4e30c09.png">

**Comment by Nazarah** [comment]
**3. Sandbox**

Sandbox shows the **CORS enabled Endpoint** (if any) for the API, **Current status** of the API (Operational / slight degradation in performance, etc.) in sandbox environment, **Response time** and **runkit UI** (if integrated) to try out example calls to the Sandbox.

<img width="356" alt="Screen Shot 2019-05-08 at 12 23 41" src="https://user-images.githubusercontent.com/17976243/57364568-21ec3880-718c-11e9-90ff-33e755bd4053.png">


![Screen Shot 2019-05-08 at 12 24 30](https://user-images.githubusercontent.com/17976243/57364585-2b75a080-718c-11e9-9b5f-a259e4b836a0.png)


**Question:** 
* Status measurement --> via ping request-respond to see if it is iIve or not? 
* If so, what is the time interval to check this? 
* API Response time to measure performance? 
* If so, what are the threshold values? (i.g. for Operational, Slightly Degraded Performance, Down, etc.)

**Comment by Nazarah** [comment]
### Mobile wireframes V2

**1. General**
<img width="790" alt="Screenshot 2019-05-17 at 14 54 17" src="https://user-images.githubusercontent.com/17976243/57926819-fd433f80-78b4-11e9-99d0-4e18ae505f06.png">


**2. Sandbox**
<img width="799" alt="Screenshot 2019-05-17 at 14 54 33" src="https://user-images.githubusercontent.com/17976243/57926834-046a4d80-78b5-11e9-8a6c-cb2f660cf635.png">

<img width="1196" alt="Screenshot 2019-05-17 at 15 05 17" src="https://user-images.githubusercontent.com/17976243/57926902-3b406380-78b5-11e9-8107-d24aed7d1b2f.png">


**3. Resources**
<img width="356" alt="Screenshot 2019-05-17 at 14 55 17" src="https://user-images.githubusercontent.com/17976243/57926916-4bf0d980-78b5-11e9-8a4d-433dbbc98603.png">


**4. Analytics**
<img width="829" alt="Screenshot 2019-05-17 at 14 55 41" src="https://user-images.githubusercontent.com/17976243/57926937-59a65f00-78b5-11e9-8b2d-5c1f305c6440.png">


**5. Feedback**
<img width="788" alt="Screenshot 2019-05-17 at 14 56 04" src="https://user-images.githubusercontent.com/17976243/57926950-62973080-78b5-11e9-9609-dc1fba0e79af.png">

**Comment by Nazarah** [comment]
### Desktop Wireframes V2

**1. General**
<img width="661" alt="Screenshot 2019-05-17 at 14 59 57" src="https://user-images.githubusercontent.com/17976243/57927935-21545000-78b8-11e9-9824-24bb318d1c6b.png">

2. **Sandbox**
<img width="655" alt="Screenshot 2019-05-17 at 15 00 24" src="https://user-images.githubusercontent.com/17976243/57927956-2addb800-78b8-11e9-8c91-0b07ebd7382e.png">

**3. Resources**
<img width="650" alt="Screenshot 2019-05-17 at 15 00 45" src="https://user-images.githubusercontent.com/17976243/57927966-30d39900-78b8-11e9-8116-3953b6f9c100.png">

**4. Analytics - Production**
<img width="654" alt="Screenshot 2019-05-17 at 15 01 03" src="https://user-images.githubusercontent.com/17976243/57927997-41840f00-78b8-11e9-988b-817f62c9ebef.png">

**5. Feedback**
<img width="654" alt="Screenshot 2019-05-17 at 15 01 31" src="https://user-images.githubusercontent.com/17976243/57928017-48128680-78b8-11e9-9711-51082467bbe4.png">

**Comment by kyyberi** [comment]
In the desktop version remove the left toolbar / menu. The page has so many menus that users are probably confused easily. Otherwise I would go for it.

**Comment by kyyberi** [comment]
Review from @MikaHamalainen as well is needed

**Comment by Nazarah** [comment]
reply to [comment](https://github.com/PlatformOfTrust/pot-websites/issues/96#issuecomment-494015360)

### Desktop wireframes version 3

Continuous scrolling of contents.
API name, metadata, CTAs (runkit and documentation) are sticky.
Expanse/collapse of specific sections (optional) 

**1. General**

<img width="801" alt="Screenshot 2019-05-22 at 10 29 20" src="https://user-images.githubusercontent.com/17976243/58155733-2c72fb80-7c7d-11e9-8b6b-8325c0e9d0fa.png">


**2. Sandbox**

<img width="809" alt="Screenshot 2019-05-22 at 10 29 51" src="https://user-images.githubusercontent.com/17976243/58155746-339a0980-7c7d-11e9-80c9-323f6669b5b4.png">

**3. Resources**

<img width="806" alt="Screenshot 2019-05-22 at 10 30 10" src="https://user-images.githubusercontent.com/17976243/58155765-3eed3500-7c7d-11e9-9257-34d4aa2287af.png">


**4. Analytics - Production**

<img width="794" alt="Screenshot 2019-05-22 at 10 30 29" src="https://user-images.githubusercontent.com/17976243/58155792-4dd3e780-7c7d-11e9-9bb0-f8ba3cccb7b0.png">

**5. Feedback**

<img width="800" alt="Screenshot 2019-05-22 at 10 30 52" src="https://user-images.githubusercontent.com/17976243/58155799-53313200-7c7d-11e9-995d-2fac4ebcb513.png">
